version: 2
jobs:
  build:
    working_directory: /go/src/github.com/Financial-Times/public-organisations-api
    docker:
      - image: circleci/golang:1.12
        environment:
          CIRCLE_TEST_REPORTS: /tmp/test-reports
          CIRCLE_ARTIFACTS: /tmp/artifacts
    steps:
      - checkout
      - run:
          name: Create folders
          command: |
            mkdir -p $CIRCLE_TEST_REPORTS/golang
            mkdir -p $CIRCLE_ARTIFACTS
      - run:
          name: Download dependancies
          command: |
            go get -u github.com/jstemmer/go-junit-report
            go get -u github.com/mattn/goveralls
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run:
          name: Download vendored dependancies
          command: |
            dep ensure -v -vendor-only
      - run:
          name: Build app
          command: |
            go build -v
      - run:
          name: Run tests and create coverage report
          command: |
            go test ./... -race -cover -coverprofile=$CIRCLE_TEST_REPORTS/coverage.out | go-junit-report > $CIRCLE_TEST_REPORTS/golang/junit.xml
      - run:
          name: Upload coverage report
          command: |
            /go/bin/goveralls -coverprofile=$CIRCLE_TEST_REPORTS/coverage.out -service=circle-ci -repotoken=$COVERALLS_TOKEN
      - store_test_results:
          path: /tmp/test-reports
  docker_build:
    working_directory: /public-organisations-api
    docker:
      - image: docker:18.03
    steps:
      - checkout
      - setup_docker_engine
      - run:
          name: Build Dockerfile
          command: docker build .
  dredd:
    working_directory: /go/src/github.com/Financial-Times/public-organisations-api
    docker:
      - image: bankrs/golang-dredd:go1.10.0-dredd5.0.0
        environment:
          GOPATH: /go
          CONCEPTS_API: http://localhost:9000
      - image: peteclarkft/ersatz:stable
    steps:
      - checkout
      - run:
          name: External Dependencies
          command: |
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            go get -u github.com/mattn/goveralls
            go get -u github.com/jstemmer/go-junit-report
      - run:
          name: Load ersatz-fixtures.yml to ersatz image
          command: "curl -X POST --data-binary @_ft/ersatz-fixtures.yml -H \"Content-type: text/x-yaml\" http://localhost:9000/__configure"
      - run:
          name: Import libraries
          command: dep ensure -v -vendor-only
      - run:
          name: Go Build
          command: go build -v
      - run:
          name: Dredd API Testing
          command: dredd

workflows:
  version: 2
  tests_and_docker:
    jobs:
      - build
      - dredd
      - docker_build:
          requires:
            - build
